version: "3.9"

services:
  app:
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_DATASOURCE_USER=postgres
    depends_on:
      - postgres_db
    ports:
      - "8080:8080"


  postgres_db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"