CREATE TABLE file
(
    file_id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title         VARCHAR(255),
    file          VARCHAR(255),
    description   VARCHAR(255),
    creation_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_file PRIMARY KEY (file_id)
);